name: ds_test_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^14.3.0
  retrofit: ^4.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  svg_flutter: ^0.0.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  email_validator: ^3.0.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  retrofit_generator: ^9.1.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
